name: build
on:
  - push
jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: "Build Image"
        run: docker image build --tag=project_jee:latest ./
      - name: "run containers"
        run: docker run -d --rm --name=projectJeeBuilder project_jee:latest
      - name: "check containers"
        run: docker ps
      - name: "stop containers"
        run: docker stop projectJeeBuilder
  deploy:
    needs: build_image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: megacretin
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: megacretin/docker-projet-jee:${{ github.ref_name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: contains('refs/heads/main', github.ref)
        with:
          username: megacretin
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        if: contains('refs/heads/main', github.ref)
        with:
          push: true
          context: ./
          tags: megacretin/docker-projet-jee:latest